"""ConversationAgentState — structured typed dict for Core conversation ConversationGraph."""

from typing import Any, TypedDict


class ConversationAgentState(TypedDict, total=False):
    """Core conversation Agent State for a single ConversationRun.

    Each node reads/writes specific fields. All values must be JSON-serializable
    for trace_steps recording.
    """

    # ── identity ────────────────────────────────────────────────────
    user_id: str
    companion_id: str
    conversation_id: str
    user_input: str
    current_mode: str  # ModeKey

    # ── database record IDs ─────────────────────────────────────────
    user_message_id: str
    assistant_message_id: str
    trace_run_id: str

    # ── context (loaded by InputNode) ───────────────────────────────
    companion_profile: dict[str, Any]
    boundary_settings: dict[str, Any]
    conversation: dict[str, Any]
    recent_messages: list[dict[str, Any]]
    context_pack_manifest: dict[str, Any]
    tool_intent: dict[str, Any]
    tool_observations: list[dict[str, Any]]
    tool_loop: dict[str, Any]
    retrieval_tool_context: dict[str, Any]
    task_run: dict[str, Any]
    task_context: dict[str, Any]
    task_runtime_handled: bool

    # ── memory ──────────────────────────────────────────────────────
    retrieved_memories: list[dict[str, Any]]
    selected_memories: list[dict[str, Any]]

    # ── response ────────────────────────────────────────────────────
    response_strategy: dict[str, Any]
    assistant_response: str

    # ── candidates (generated by Agent) ─────────────────────────────
    memory_candidates: list[dict[str, Any]]
    growth_candidates: list[dict[str, Any]]
    presence_opportunities: list[dict[str, Any]]

    # ── checks ──────────────────────────────────────────────────────
    boundary_check: dict[str, Any]

    # ── trace ───────────────────────────────────────────────────────
    trace_steps: list[dict[str, Any]]
    turn_stage_timings: list[dict[str, Any]]
    errors: list[dict[str, Any]]
    warnings: list[str]

    # ── Continuity: feedback / calibration ──────────────────────────────
    recent_feedback_events: list[dict[str, Any]]
    feedback_summary: dict[str, Any]

    # ── Continuity: memory usage / impact ───────────────────────────────
    memory_usage_event_ids: list[str]
    memory_lifecycle_event_ids: list[str]
    memory_impact_summary: dict[str, Any]

    # Unified, read-only context contract for one Companion turn.
    companion_context_snapshot: dict[str, Any]

    # durable turn: durable turn identity and unified domain-effect receipts
    turn_idempotency_key: str
    post_turn_effects: dict[str, Any]
    post_turn_effect_errors: list[dict[str, Any]]
    room_turn_id: str
    room_turn_step_id: str
    context_document_ids: list[str]

    # ── Continuity: continuity ──────────────────────────────────────────
    continuity_snapshot_id: str
    continuity_summary: dict[str, Any]

    # ── Continuity: user state ──────────────────────────────────────────
    user_state_snapshot_id: str

    # ── Continuity: relationship ────────────────────────────────────────
    relationship_explanation_ids: list[str]
    relationship_candidates: list[dict[str, Any]]

    # Companion affect: Companion affect is separate from user/relationship state
    affect_state: dict[str, Any]
    affect_events: list[dict[str, Any]]

    # ── Continuity: review ──────────────────────────────────────────────
    review_batch_id: str
    review_summary: dict[str, Any]

    # ── provider info ───────────────────────────────────────────────
    provider_mode: str
    provider_name: str
    model_name: str
    provider_timing: dict[str, Any]
    reasoning_policy: dict[str, Any]
    requested_reasoning_mode: str
    stream_response: bool
    defer_post_turn_effects: bool
    turn_cancelled: bool

    # ── Continuity: provider ────────────────────────────────────────────
    embedding_provider: str

    # Agent execution: tool / file / project / evidence / strategy signals
    tool_runs: list[dict[str, Any]]
    tool_run_ids: list[str]
    tool_context: dict[str, Any]
    file_evidence: list[dict[str, Any]]
    file_context_usage_ids: list[str]
    evidence_sufficiency_events: list[dict[str, Any]]
    evidence_sufficiency_event_ids: list[str]
    project_task_updates: list[dict[str, Any]]
    outdated_memory_flags: list[dict[str, Any]]
    outdated_memory_flag_ids: list[str]
    growth_consistency_checks: list[dict[str, Any]]
    growth_consistency_check_ids: list[str]
    bad_case_signals: list[dict[str, Any]]
    bad_case_signal_ids: list[str]
    evaluation_signals: list[dict[str, Any]]
    evaluation_signal_ids: list[str]
    memory_reranker_run_ids: list[str]
    presence_policy_run_ids: list[str]
    llm_call_record_ids: list[str]
    execution_signal_summary: dict[str, Any]

    # Companion Reoriented: multi-companion / co-presence context
    active_companion: dict[str, Any]
    co_present_companions: list[dict[str, Any]]
    co_presence_session: dict[str, Any]
    participant_awareness: dict[str, Any]
    shared_scene: dict[str, Any]
    companion_memory_scope: dict[str, Any]
    shared_memory_candidates: list[dict[str, Any]]
    cross_companion_memory_reviews: list[dict[str, Any]]
    persona_guard_result: dict[str, Any]
    delegation_intent: dict[str, Any]
    companion_context_summary: dict[str, Any]


class RealtimeAgentState(TypedDict, total=False):
    """Realtime compatibility RealtimeSessionGraph state.

    The realtime graph is additive. It records co-presence events into the
    Realtime compatibility realtime trace tables and links the result back to TraceRun without
    changing ConversationGraph V4 behavior.
    """

    user_id: str
    companion_id: str
    realtime_session_id: str
    realtime_trace_session_id: str
    trace_run_id: str
    default_channel_id: str
    hard_stop_scope: str
    hard_stop_target_id: str

    realtime_session: dict[str, Any]
    realtime_participants: list[dict[str, Any]]
    realtime_channels: list[dict[str, Any]]
    participant_awareness: dict[str, Any]
    channel_event_summary: dict[str, Any]
    voice_turn_trace: dict[str, Any]
    multimodal_permission: dict[str, Any]
    realtime_memory_gate: dict[str, Any]
    shared_moment_candidate: dict[str, Any]
    resident_presence: dict[str, Any]
    scoped_hard_stop: dict[str, Any]
    realtime_replay: dict[str, Any]
    redaction: dict[str, Any]
    realtime_trace_summary: dict[str, Any]

    realtime_trace_event_ids: list[str]
    permission_audit_event_ids: list[str]
    memory_gate_trace_ids: list[str]
    redaction_event_ids: list[str]
    replay_segment_ids: list[str]
    trace_steps: list[dict[str, Any]]
    errors: list[dict[str, Any]]
    warnings: list[str]
